"use client";
import { createContext, useContext, useEffect, useMemo, useState } from "react";

export type CartProduct={id:string;name:string;price:string;category:string;description?:string};
export type CartLine=CartProduct & {quantity:number;unitPrice:number};
export type HotelDeliveryDetails={orderReference:string;createdAt:string;guestName:string;phone:string;location:"room"|"pool";floor?:string;room?:string;poolDetails?:string;instructions?:string};
type CartContextValue={items:CartLine[];itemCount:number;subtotal:number;hotelDelivery:HotelDeliveryDetails|undefined;addItem:(product:CartProduct)=>void;increase:(id:string)=>void;decrease:(id:string)=>void;remove:(id:string)=>void;clear:()=>void;setHotelDelivery:(details:HotelDeliveryDetails)=>void};
const CartContext=createContext<CartContextValue|undefined>(undefined);
const STORAGE_KEY="de-vihelhana-cart";
const HOTEL_DELIVERY_STORAGE_KEY="de-vihelhana-hotel-delivery";
const priceToNumber=(price:string)=>Number(price.replace(/[^0-9.]/g,""));
export const formatPrice=(amount:number)=>`€${amount.toFixed(2)}`;
const persist=(items:CartLine[])=>{try{localStorage.setItem(STORAGE_KEY,JSON.stringify(items))}catch{}};

export function CartProvider({children}:{children:React.ReactNode}){const[items,setItems]=useState<CartLine[]>([]);const[hotelDelivery,setHotelDeliveryState]=useState<HotelDeliveryDetails>();const[ready,setReady]=useState(false);useEffect(()=>{try{const saved=localStorage.getItem(STORAGE_KEY);if(saved)setItems(JSON.parse(saved));const savedDelivery=localStorage.getItem(HOTEL_DELIVERY_STORAGE_KEY);if(savedDelivery)setHotelDeliveryState(JSON.parse(savedDelivery));}catch{}finally{setReady(true)}},[]);useEffect(()=>{if(ready)persist(items)},[items,ready]);const value=useMemo<CartContextValue>(()=>({items,itemCount:items.reduce((count,item)=>count+item.quantity,0),subtotal:items.reduce((total,item)=>total+item.unitPrice*item.quantity,0),hotelDelivery,addItem(product){setItems(current=>{const existing=current.find(item=>item.id===product.id);const next=existing?current.map(item=>item.id===product.id?{...item,quantity:item.quantity+1}:item):[...current,{...product,unitPrice:priceToNumber(product.price),quantity:1}];persist(next);return next})},increase(id){setItems(current=>{const next=current.map(item=>item.id===id?{...item,quantity:item.quantity+1}:item);persist(next);return next})},decrease(id){setItems(current=>{const next=current.flatMap(item=>item.id===id?(item.quantity===1?[]:[{...item,quantity:item.quantity-1}]):[item]);persist(next);return next})},remove(id){setItems(current=>{const next=current.filter(item=>item.id!==id);persist(next);return next})},clear(){setItems(()=>{persist([]);return[]});setHotelDeliveryState(undefined);try{localStorage.removeItem(HOTEL_DELIVERY_STORAGE_KEY)}catch{}},setHotelDelivery(details){setHotelDeliveryState(details);try{localStorage.setItem(HOTEL_DELIVERY_STORAGE_KEY,JSON.stringify(details))}catch{}}}),[items,hotelDelivery]);return <CartContext.Provider value={value}>{children}</CartContext.Provider>}
export function useCart(){const context=useContext(CartContext);if(!context)throw new Error("useCart must be used inside CartProvider");return context}
