"use client";

import { Bell, BellRing, Check, ChevronDown, ChevronUp, LoaderCircle, LogOut, MapPin, RefreshCw, Search, Volume2, VolumeX } from "lucide-react";
import { useCallback, useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import type { RestaurantStatus, StaffOrder, StaffPaymentStatus } from "@/lib/staff-orders";

type Summary = { newOrders: number; activeOrders: number; completedToday: number; paidOrdersToday: number; paidSalesToday: number; preparingOrders: number; readyOrders: number; deliveredToday: number };
type DashboardData = { orders: StaffOrder[]; page: number; pageSize: number; total: number; summary: Summary; newPaidOrderIds: string[] };
const tabs: Array<"ALL" | RestaurantStatus> = ["ALL", "NEW", "ACCEPTED", "PREPARING", "READY", "DELIVERED", "CANCELLED"];
const nextActions: Partial<Record<RestaurantStatus, { status: RestaurantStatus; label: string; tone?: string }>> = { NEW: { status: "ACCEPTED", label: "Accept order" }, ACCEPTED: { status: "PREPARING", label: "Start preparing" }, PREPARING: { status: "READY", label: "Mark ready" }, READY: { status: "DELIVERED", label: "Mark delivered" } };
const formatMoney = (cents: number) => new Intl.NumberFormat("en-MT", { style: "currency", currency: "EUR" }).format(cents / 100);
const maltaTime = (value: string) => new Intl.DateTimeFormat("en-MT", { timeZone: "Europe/Malta", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const statusTone: Record<RestaurantStatus, string> = { NEW: "bg-gold/20 text-forest", ACCEPTED: "bg-blue-100 text-blue-800", PREPARING: "bg-orange-100 text-orange-800", READY: "bg-emerald-100 text-emerald-800", DELIVERED: "bg-forest text-cream", CANCELLED: "bg-stone-200 text-stone-700" };

function OrderCard({ order, onUpdate, working }: { order: StaffOrder; onUpdate: (id: string, status: RestaurantStatus) => void; working: boolean }) {
  const [expanded, setExpanded] = useState(false);
  const action = nextActions[order.restaurantStatus];
  const paid = order.paymentStatus === "PAID";
  return <article className={`rounded-[1.5rem] border p-5 shadow-sm transition sm:p-6 ${order.restaurantStatus === "NEW" && paid ? "border-gold bg-gold/10" : "border-earth/15 bg-cream/75"}`}>
    <div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><span className={`rounded-full px-3 py-1 text-[10px] font-bold tracking-[.14em] ${statusTone[order.restaurantStatus]}`}>{order.restaurantStatus}</span><span className={`rounded-full px-3 py-1 text-[10px] font-bold tracking-[.14em] ${paid ? "bg-emerald-100 text-emerald-800" : "bg-red-50 text-red-700"}`}>{paid ? "PAID ONLINE ✓" : "PENDING PAYMENT"}</span></div><h2 className="mt-3 font-display text-2xl">{order.orderNumber}</h2><p className="mt-1 text-xs text-forest/60">{maltaTime(order.createdAt)} · Malta time</p></div><p className="font-display text-2xl text-earth">{formatMoney(order.totalInCents)}</p></div>
    <div className={`mt-5 rounded-2xl p-4 ${order.deliveryType === "hotel-room" ? "bg-forest text-cream" : "bg-beige/70 text-forest"}`}><p className={`text-[10px] font-semibold tracking-[.18em] ${order.deliveryType === "hotel-room" ? "text-clay" : "text-earth"}`}>{order.deliveryType === "hotel-room" ? "ROOM DELIVERY" : order.deliveryType === "pool-area" ? "POOL SIDE" : "PICKUP"}</p>{order.deliveryType === "hotel-room" ? <p className="mt-2 font-display text-xl">Room {order.room || "—"} <span className="text-sm">· Floor {order.floor || "—"}</span></p> : order.deliveryType === "pool-area" ? <p className="mt-2 flex items-center gap-2 font-display text-xl"><MapPin size={18}/>Pool side{order.poolLocationDetails ? ` · ${order.poolLocationDetails}` : ""}</p> : <p className="mt-2 font-display text-xl">Collection order</p>}</div>
    <div className="mt-5"><p className="eyebrow">Guest & order</p>{order.customerName && <p className="mt-2 text-sm font-semibold">{order.customerName}{order.customerPhone ? ` · ${order.customerPhone}` : ""}</p>}<ul className="mt-3 space-y-1.5 text-sm">{order.items.map((item) => <li key={`${item.productId}-${item.name}`} className="flex justify-between gap-3"><span>{item.quantity} × {item.name}</span><span className="shrink-0 text-earth">{formatMoney(item.totalInCents)}</span></li>)}</ul>{order.customerNotes && <p className="mt-4 border-l-2 border-earth/40 pl-3 text-sm leading-6 text-forest/75"><strong>Notes:</strong> {order.customerNotes}</p>}</div>
    <button onClick={() => setExpanded(!expanded)} className="focus-ring mt-5 inline-flex items-center gap-1 text-xs font-semibold tracking-[.12em] text-earth hover:text-forest">{expanded ? <ChevronUp size={15}/> : <ChevronDown size={15}/>}{expanded ? "HIDE DETAILS" : "VIEW DETAILS"}</button>
    {expanded && <div className="mt-4 grid gap-2 border-t border-earth/15 pt-4 text-xs leading-5 text-forest/70"><p><strong>Created:</strong> {new Intl.DateTimeFormat("en-MT", { timeZone: "Europe/Malta", dateStyle: "medium", timeStyle: "short" }).format(new Date(order.createdAt))}</p>{order.customerEmail && <p><strong>Email:</strong> {order.customerEmail}</p>}{order.stripeCheckoutSessionId && <p className="break-all"><strong>Stripe session:</strong> {order.stripeCheckoutSessionId}</p>}</div>}
    <div className="mt-6 flex flex-wrap gap-3">{action && <button disabled={!paid || working} onClick={() => onUpdate(order.id, action.status)} className="focus-ring min-h-11 rounded-full bg-forest px-5 py-3 text-xs font-semibold tracking-[.13em] text-cream transition hover:bg-earth disabled:cursor-not-allowed disabled:opacity-45">{working ? "UPDATING…" : action.label.toUpperCase()}</button>}{["NEW", "ACCEPTED", "PREPARING", "READY"].includes(order.restaurantStatus) && <button disabled={!paid || working} onClick={() => onUpdate(order.id, "CANCELLED")} className="focus-ring min-h-11 rounded-full border border-red-300 px-5 py-3 text-xs font-semibold tracking-[.13em] text-red-700 disabled:cursor-not-allowed disabled:opacity-45">CANCEL ORDER</button>}{!paid && <span className="self-center text-xs text-red-700">Awaiting verified Stripe payment</span>}</div>
  </article>;
}

export function StaffOrdersDashboard() {
  const router = useRouter();
  const [status, setStatus] = useState<"ALL" | RestaurantStatus>("NEW");
  const [payment, setPayment] = useState<"ALL" | StaffPaymentStatus>("ALL");
  const [search, setSearch] = useState(""); const [date, setDate] = useState("");
  const [data, setData] = useState<DashboardData>(); const [loading, setLoading] = useState(true); const [error, setError] = useState(""); const [updating, setUpdating] = useState("");
  const [soundEnabled, setSoundEnabled] = useState(false); const [notice, setNotice] = useState("");
  const seenIds = useRef(new Set<string>()); const initialized = useRef(false);
  const playSound = useCallback(() => { try { const context = new AudioContext(); const oscillator = context.createOscillator(); const gain = context.createGain(); oscillator.frequency.value = 740; gain.gain.setValueAtTime(0.06, context.currentTime); gain.gain.exponentialRampToValueAtTime(0.001, context.currentTime + 0.22); oscillator.connect(gain).connect(context.destination); oscillator.start(); oscillator.stop(context.currentTime + 0.22); } catch {} }, []);
  const handleNotifications = useCallback((ids: string[]) => { const stored = new Set<string>(JSON.parse(localStorage.getItem("dv-staff-seen-paid-orders") || "[]")); if (!initialized.current) { ids.forEach((id) => stored.add(id)); seenIds.current = stored; initialized.current = true; localStorage.setItem("dv-staff-seen-paid-orders", JSON.stringify([...stored].slice(-200))); return; } const fresh = ids.filter((id) => !seenIds.current.has(id)); if (!fresh.length) return; fresh.forEach((id) => seenIds.current.add(id)); localStorage.setItem("dv-staff-seen-paid-orders", JSON.stringify([...seenIds.current].slice(-200))); setNotice(`${fresh.length} new paid order${fresh.length === 1 ? "" : "s"} received`); if (soundEnabled) playSound(); if (soundEnabled && "Notification" in window && Notification.permission === "granted") new Notification("De Vilhena Bistrot", { body: `${fresh.length} new paid order${fresh.length === 1 ? "" : "s"} is waiting.` }); }, [playSound, soundEnabled]);
  const load = useCallback(async (silent = false) => { if (!silent) setLoading(true); try { const params = new URLSearchParams(); if (status !== "ALL") params.set("status", status); if (payment !== "ALL") params.set("payment", payment); if (search.trim()) params.set("search", search.trim()); if (date) params.set("date", date); const response = await fetch(`/api/staff/orders?${params}`, { cache: "no-store" }); if (response.status === 401) { router.replace("/staff/login"); return; } const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to load orders."); setData(payload); handleNotifications(payload.newPaidOrderIds); setError(""); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to load orders."); } finally { if (!silent) setLoading(false); } }, [date, handleNotifications, payment, router, search, status]);
  useEffect(() => { const stored = localStorage.getItem("dv-staff-sound-enabled") === "true"; setSoundEnabled(stored); load(); const timer = window.setInterval(() => load(true), 15000); return () => window.clearInterval(timer); }, [load]);
  async function updateStatus(id: string, nextStatus: RestaurantStatus) { setUpdating(id); try { const response = await fetch(`/api/staff/orders/${id}/status`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status: nextStatus }) }); const payload = await response.json(); if (!response.ok) throw new Error(payload.error || "Unable to update order."); await load(true); } catch (reason) { setError(reason instanceof Error ? reason.message : "Unable to update order."); } finally { setUpdating(""); } }
  async function toggleSound() { const next = !soundEnabled; if (next && "Notification" in window && Notification.permission === "default") await Notification.requestPermission(); localStorage.setItem("dv-staff-sound-enabled", String(next)); setSoundEnabled(next); if (next) playSound(); }
  async function logout() { await fetch("/api/staff/auth/logout", { method: "POST" }); router.replace("/staff/login"); router.refresh(); }
  const summary = data?.summary;
  return <main className="min-h-screen px-4 pb-16 pt-28 sm:px-6 lg:px-10"><div className="mx-auto max-w-7xl"><header className="flex flex-col gap-5 border-b border-earth/15 pb-7 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">De Vilhena Bistrot</p><h1 className="mt-3 font-display text-4xl sm:text-5xl">Staff Order <i className="text-earth">Dashboard.</i></h1><p className="mt-3 text-sm text-forest/65">Live operations view · Malta time</p></div><div className="flex flex-wrap gap-2"><button onClick={toggleSound} className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-full border border-earth/25 px-4 text-xs font-semibold tracking-[.12em] text-forest">{soundEnabled ? <Volume2 size={16}/> : <VolumeX size={16}/>}{soundEnabled ? "ALERTS ON" : "ENABLE ALERTS"}</button><button onClick={() => load()} className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-full border border-earth/25 px-4 text-xs font-semibold tracking-[.12em] text-forest"><RefreshCw size={15}/>REFRESH</button><button onClick={logout} className="focus-ring inline-flex min-h-11 items-center gap-2 rounded-full border border-earth/25 px-4 text-xs font-semibold tracking-[.12em] text-forest"><LogOut size={15}/>SIGN OUT</button></div></header>
    {notice && <div role="status" className="mt-5 flex items-center gap-3 rounded-2xl bg-gold/20 p-4 text-sm font-semibold text-forest"><BellRing size={19}/>{notice}<button onClick={() => setNotice("")} className="ml-auto text-xs underline">DISMISS</button></div>}
    <section className="mt-7 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><div className="rounded-2xl bg-forest p-5 text-cream"><p className="text-[10px] font-semibold tracking-[.18em] text-clay">NEW ORDERS</p><p className="mt-2 font-display text-4xl">{summary?.newOrders ?? "—"}</p></div><div className="rounded-2xl bg-beige/65 p-5"><p className="eyebrow">Active orders</p><p className="mt-2 font-display text-4xl">{summary?.activeOrders ?? "—"}</p></div><div className="rounded-2xl bg-beige/65 p-5"><p className="eyebrow">Completed today</p><p className="mt-2 font-display text-4xl">{summary?.completedToday ?? "—"}</p></div><div className="rounded-2xl bg-earth p-5 text-cream"><p className="text-[10px] font-semibold tracking-[.18em] text-clay">Today’s paid sales</p><p className="mt-2 font-display text-4xl">{summary ? formatMoney(summary.paidSalesToday) : "—"}</p><p className="mt-1 text-xs text-cream/70">{summary?.paidOrdersToday ?? 0} paid orders</p></div></section>
    <section className="mt-8 rounded-[1.5rem] border border-earth/15 bg-cream/65 p-4 sm:p-6"><div className="flex flex-wrap gap-2">{tabs.map((tab) => <button key={tab} onClick={() => setStatus(tab)} className={`focus-ring min-h-10 rounded-full px-4 text-xs font-semibold tracking-[.12em] ${status === tab ? "bg-forest text-cream" : "border border-earth/20 text-forest"}`}>{tab}</button>)}</div><div className="mt-5 grid gap-3 md:grid-cols-[1fr_auto_auto]"><label className="relative"><Search className="absolute left-3 top-3 text-earth" size={16}/><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Order number or room" className="focus-ring min-h-11 w-full rounded-full border border-earth/20 bg-transparent py-2 pl-9 pr-4 text-sm" /></label><select value={payment} onChange={(event) => setPayment(event.target.value as "ALL" | StaffPaymentStatus)} className="focus-ring min-h-11 rounded-full border border-earth/20 bg-transparent px-4 text-sm"><option value="ALL">All payments</option><option value="PAID">Paid online</option><option value="PENDING">Pending payment</option></select><input type="date" value={date} onChange={(event) => setDate(event.target.value)} className="focus-ring min-h-11 rounded-full border border-earth/20 bg-transparent px-4 text-sm" /></div></section>
    <div className="mt-7 flex items-center justify-between"><p className="eyebrow">{data ? `${data.total} matching orders` : "Loading orders"}</p>{loading && <LoaderCircle className="animate-spin text-earth" size={19}/>}</div>{error && <p role="alert" className="mt-4 rounded-xl bg-red-50 p-4 text-sm text-red-700">{error}</p>}<section className="mt-4 grid gap-4 lg:grid-cols-2">{data?.orders.map((order) => <OrderCard key={order.id} order={order} onUpdate={updateStatus} working={updating === order.id} />)}</section>{!loading && data && !data.orders.length && <div className="mt-4 rounded-[1.5rem] border border-earth/15 p-10 text-center"><Bell className="mx-auto text-earth"/><p className="mt-4 font-display text-2xl">No orders here.</p><p className="mt-2 text-sm text-forest/65">Try another status, payment, date, or search filter.</p></div>}</div></main>;
}
