import { getDatabase } from "@/lib/db";
import type { AccountStatus } from "@/lib/staff-auth";

export type ManagedStaffUser = { id: string; fullName: string; email: string; accountStatus: AccountStatus; createdAt: string; approvedAt?: string; rejectedAt?: string; disabledAt?: string };
type StaffRow = { id: string; full_name: string; email: string; account_status: AccountStatus; created_at: string | Date; approved_at: string | Date | null; rejected_at: string | Date | null; disabled_at: string | Date | null };
export type StaffAccountAction = "APPROVE" | "REJECT" | "DISABLE" | "REENABLE";
export class AdminStaffError extends Error { constructor(message: string, readonly statusCode: number) { super(message); } }

function mapStaff(row: StaffRow): ManagedStaffUser { return { id: row.id, fullName: row.full_name, email: row.email, accountStatus: row.account_status, createdAt: new Date(row.created_at).toISOString(), ...(row.approved_at ? { approvedAt: new Date(row.approved_at).toISOString() } : {}), ...(row.rejected_at ? { rejectedAt: new Date(row.rejected_at).toISOString() } : {}), ...(row.disabled_at ? { disabledAt: new Date(row.disabled_at).toISOString() } : {}) }; }
export async function getManagedStaff() { const sql = getDatabase(); const rows = await sql`SELECT id, full_name, email, account_status, created_at, approved_at, rejected_at, disabled_at FROM staff_users WHERE role = 'STAFF' ORDER BY CASE account_status WHEN 'PENDING' THEN 0 WHEN 'APPROVED' THEN 1 WHEN 'DISABLED' THEN 2 ELSE 3 END, created_at DESC LIMIT 200` as StaffRow[]; const staff = rows.map(mapStaff); return { staff, summary: { pending: staff.filter((user) => user.accountStatus === "PENDING").length, approved: staff.filter((user) => user.accountStatus === "APPROVED").length, disabled: staff.filter((user) => user.accountStatus === "DISABLED").length } }; }
const allowed: Record<StaffAccountAction, AccountStatus[]> = { APPROVE: ["PENDING", "REJECTED"], REJECT: ["PENDING"], DISABLE: ["APPROVED"], REENABLE: ["DISABLED"] };
const nextStatus: Record<StaffAccountAction, AccountStatus> = { APPROVE: "APPROVED", REJECT: "REJECTED", DISABLE: "DISABLED", REENABLE: "APPROVED" };
export async function updateManagedStaff(userId: string, action: StaffAccountAction, adminId: string) { const sql = getDatabase(); const rows = await sql`SELECT id, full_name, email, account_status, created_at, approved_at, rejected_at, disabled_at FROM staff_users WHERE id = ${userId} AND role = 'STAFF' LIMIT 1` as StaffRow[]; const user = rows[0]; if (!user) throw new AdminStaffError("Staff account not found.", 404); if (!allowed[action].includes(user.account_status)) throw new AdminStaffError("That account action is not allowed.", 409); const status = nextStatus[action]; await sql`UPDATE staff_users SET account_status = ${status}, updated_at = NOW(), approved_at = CASE WHEN ${action} IN ('APPROVE', 'REENABLE') THEN NOW() ELSE approved_at END, approved_by = CASE WHEN ${action} IN ('APPROVE', 'REENABLE') THEN ${adminId}::uuid ELSE approved_by END, rejected_at = CASE WHEN ${action} = 'REJECT' THEN NOW() ELSE rejected_at END, rejected_by = CASE WHEN ${action} = 'REJECT' THEN ${adminId}::uuid ELSE rejected_by END, disabled_at = CASE WHEN ${action} = 'DISABLE' THEN NOW() ELSE disabled_at END, disabled_by = CASE WHEN ${action} = 'DISABLE' THEN ${adminId}::uuid ELSE disabled_by END WHERE id = ${userId} AND role = 'STAFF' AND account_status = ${user.account_status}`; return { id: userId, accountStatus: status }; }
